### ISSUE TITLE
wish: add request-promises compatibility

### ISSUE THREAD

**Issue by nahuel** [googleapis/teeny-request#135]
`request-promise` (and `request-promise-native`) was deprecated along `request`. It will be nice to add a `request-promise` compatibility layer to `teeny-request`. 
 
https://github.com/request/request-promise

**Comment by bcoe** [comment]
:wave: @nahuel I am not personally familiar with `request-promise`, perhaps you could provide some sample code of what you're picturing.

**Comment by nahuel** [comment]
something like:

```js
import {teenyRequest as request} from 'teeny-request';
try { 
    const {statusCode} = await request({uri: 'http://ip.jsontest.com/'})
    console.log('statusCode:', statusCode)
} catch(error) {
  console.log('error:', error);
}
```

You can see the full API in the `request-promise` documentation.

**Comment by zamnuts** [comment]
1. Lack of a callback param assumes a stream is wanted, so a readable is returned.
2. Callbacks use 2 parameters: `Response` and `body`

Both of these would make `teeny-request`'s default signature incompatible with promises. Even promisification wouldn't work without turning the successful callback signature into a tuple.

`teeny-request` would have to provide a new and separate API to accommodate, i.e. `request.promise({uri: '...'})`.

**Comment by jaimealsilva** [comment]
For promises it could be better to use node-fetch in which teeny-request is based.

**Comment by f1yn** [comment]
@nahuel I had the same need, so I ended up making a dependancy-free helper here: https://github.com/f1yn/teeny-request-promise

It wont return a stream, and there's some options that I'm still needing to port (namely request's `auth` option).

**Comment by danielbankhead** [comment]
This library is in maintenance mode - I would recommend switching to [gaxios](https://github.com/googleapis/gaxios). We're migrating libraries to use `gaxios` going forward.

**Comment by f1yn** [comment]
@danielbankhead if this is true, please update the readme of the repo and the npm package so people know they should stop using it.

There's literally no other indication of this besides your comment - so the likelihood of people thinking Google devs will still care is rather high.

**Comment by danielbankhead** [comment]
@f1yn thanks for the feedback - I agree, we can improve messaging and rollout strategy. We will update this repo shortly after migrating a few libraries. For now, we'll continue to fix critical bugs and update dependencies.
