### ISSUE TITLE
multipart with 2 or more parts never resolves, possible incorrect multiplexing

### ISSUE THREAD

**Issue by zamnuts** [googleapis/teeny-request#168]
Not sure if this is a bug or feature request: multipart is not a documented API, but code and types exist for it.

#### Environment details

  - OS: ubuntu 18.04
  - Node.js version: 10.20.1
  - npm version: 6.14.4
  - `teeny-request` version:  6.0.3

#### Steps to reproduce

A test using two strings fails. The callback is never called and mocha times out at 10s. This is likely due to the PassThrough `stream` in `createMultipartStream` (eventually `options.body`) never has `Writable.end()` called.
```javascript
  it('should support multipart with more than 2 parts', done => {
    const scope = nock(uri).post('/').reply(200, {hello: '🌍'});
    teenyRequest(
      {
        method: 'POST',
        headers: {},
        multipart: [{body: 'foo'}, {body: 'bar'}],
        uri,
      },
      (err, res, body) => {
        assert.ifError(err);
        assert.deepStrictEqual(body, {hello: '🌍'});
        scope.done();
        done();
      }
    );
  });
```

There are two other potential and related bugs:
1. Incorrect parallel stream multiplexing.
2. Multiple `stream.end()` calls.

I haven't looked into these issues, but noticed a possible problem while diagnosing the callback issue mentioned previously.

https://github.com/googleapis/teeny-request/blob/45b79fee970ff9341fff1fe0b9bc029f16696a53/src/index.ts#L173-L178

The above snippet would synchronously iterate all `multipart` input streams which effectively does:
```javascript
const stream = new PassThrough();
part1.body.pipe(stream, {end: false});
part2.body.pipe(stream, {end: false}); // multiple writes from different sources to the same stream
stream.pipe(req);

part1.body.once('end', () => stream.end());
part2.body.once('end', () => stream.end()); // multiple end calls
```

**Comment by frankyn** [comment]
I hit this today as well. IIUC there's an assumption that the first part is a type 'string' while the second part is not a 'string' / 'Readable Stream'. 

To unblock this issue for two string based parts, I did as mentioned above:

```javascript
stream.write(finale);
stream.end();
```

However does not resolve the stream case.

@fhinkel do you have pointers on how to unblock this issue?

**Comment by fhinkel** [comment]
For the multiple `stream.end()` calls, we should be able to check if the streams has been ended before.

**Comment by bcoe** [comment]
👋 calling this a feature request, since as @zamnuts points out this is not a documented API, and as @frankyn points out we have a workaround upstream.

@frankyn @stephenplusplus perhaps we could upstream this workaround into teeny-request?

**Comment by ddelgrosso1** [comment]
It is unlikely that this new feature will be added. As a result I am closing this issue. If there is strong support or if this is still wanted, please feel free to reopen or comment.
