### ISSUE TITLE
PR to fix undefined error in getAgent?

### ISSUE THREAD

**Issue by jsjoeio** [googleapis/teeny-request#236]
Hi there! 

I think I found a bug in [`getAgent`](https://github.com/googleapis/teeny-request/blob/master/src/agents.ts#L40).

Due to this [type assertion](https://github.com/googleapis/teeny-request/blob/master/src/index.ts#L120-L121), `getAgent` assumes that `uri` is defined and calls `.startsWith` which throws an error. I came to this conclusion while running into an error with [`codecov`](https://github.com/codecov/codecov-node/issues/324#issuecomment-866379405).

It looks like this type assertion came back in Nov. 2018 via [this PR](https://github.com/googleapis/teeny-request/pull/10).

I believe the simplest fix would be to change `const isHttp = uri.startsWith('http://');` -> `const isHttp = uri?.startsWith('http://');` (using the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)), which means you'd probably want to change the parameter type annotation for `uri: string` -> `uri: string | undefined` and add a test.

Would you accept a PR for this?

**Comment by bcoe** [comment]
@jsjoeio thanks for the bug report 👍

**Comment by bcoe** [comment]
_Would happily accept a PR, commented too fast._
