### ISSUE TITLE
Release please!

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/teeny-request#41]
👋 @fhinkel -- if you're willing, [this repo could move to an official Google org](https://github.com/fhinkel/teeny-request/pull/37#issuecomment-497085314) and be modernized to use some of the autorelease tools that have been put in place for the other google API repos (gcs-resumable-upload, @google-cloud/storage, etc).

**Comment by fhinkel** [comment]
Yes! How do I move it?

**Comment by fhinkel** [comment]
Yes, let's transfer it! This is a breaking release, right?

**Comment by fhinkel** [comment]
Done, 4.0 is out.

**Comment by stephenplusplus** [comment]
Sorry for my delayed replies, but yes, it was breaking and thank you!

@JustinBeckwith could you help transfer this over?

**Comment by stephenplusplus** [comment]
Looks like it moved!
