### ISSUE TITLE
Support `forever` option

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/teeny-request#48]
RE: https://github.com/googleapis/nodejs-bigquery/issues/41#issuecomment-504384070

Looks like we just need to set `keepAlive` to `true` on our agents(?), however the current proxy agent does not support said option.

**Comment by JustinBeckwith** [comment]
SGTM - @callmehiphop mind taking this one on?

**Comment by callmehiphop** [comment]
@JustinBeckwith sure, I guess the only thing I would like input on is if we are tied to the current proxy agent? Seems like we'll need to either patch it or find a new one.

**Comment by JustinBeckwith** [comment]
The only 'requirement' for that agent is that we support proxies 🤷‍♂
