### ISSUE TITLE
Need to cut a release

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/teeny-request#51]
When this library was transferred over to the googleapis org, something got lost in translation with the version number and available tags.  I tried to cut a 4.0 release in #46, but it turns out that 4.0 had already been released 😱 

@bcoe - can you figure out how to get the chances since 4.0 went out into a new release?  I think it's going to be a semver major due to the changes in #44

**Comment by bcoe** [comment]
we need to add `google-wombat` to the npm module, I believe you should have permission to do so @JustinBeckwith.

**Comment by JustinBeckwith** [comment]
Added!
