### ISSUE TITLE
[ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/teeny-request#63]
First reported: https://github.com/googleapis/nodejs-storage/issues/798

[#44](https://github.com/googleapis/teeny-request/pull/44/files#diff-f41e9d04a45c83f3b6f6e630f10117feR231) converted the returned request stream from a PassThrough stream to a Duplex stream.

@JustinBeckwith what was the motivation for that? Are we able to simply revert back to the PassThrough, or was that insufficient in some way?

**Comment by JustinBeckwith** [comment]
I honestly have no idea why in the world I did that.  Please feel free to change back.
