### ISSUE TITLE
Make stream readable

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/teeny-request#73]
Normal request streams allow you to read from them via `pipe` or `data` events. This currently is not possible here. We should support it because I think it is probably the expected behavior.

**Comment by stephenplusplus** [comment]
What went wrong with the first attempt?

**Comment by callmehiphop** [comment]
@stephenplusplus we always piped the response body into the user stream, but I think we want to do it conditionally based on whether or not the user is actually trying to read from it.

**Comment by stephenplusplus** [comment]
It seems fair to assume if the user wants stream mode (signaled by not providing a callback), they want to read from it. Am I not considering something?

**Comment by callmehiphop** [comment]
I think in its current state, it is not possible to read from yet we use it as a stream in places successfully. To me this implies that if we pipe unnecessarily we might be creating a (slow) memory leak?

**Comment by stephenplusplus** [comment]
AFAIK, our libs use teeny-request through retry-request (configured in common). retry-request gets the stream from the response event: https://github.com/stephenplusplus/retry-request/blob/6f69c95dceada6b4255c148fbd27c4d530fcec3e/index.js#L146.

But, I see the issue you're pointing out now. In the `request` library, they always piped a decorated stream back, but emitted the raw http.IncomingMessage response stream if the user needed it. So technically to be compatible as a straight conversion from request, we'd need to follow the same pattern, but I think we've come to care less about being 1:1 with request.

In any case, I think I have a solution in mind. I'll PR it up.

**Comment by stephenplusplus** [comment]
PR sent over here: #74
