### ISSUE TITLE
Request option gzip=false is not handled correctly

### ISSUE THREAD

**Issue by maxiruani** [googleapis/teeny-request#94]
[@google-cloud/bigquery](https://www.npmjs.com/package/@google-cloud/bigquery) relies on [@google-cloud/common](https://www.npmjs.com/package/@google-cloud/common) for requests, and then uses teeny-request.

I wanted to disable gzip for all requests, but it turns out that the gzip variable is not handled correctly and it never end up being assigned.

[File index.ts -> Ln 92](https://github.com/googleapis/teeny-request/blob/master/src/index.ts#L92).

```javascript
function requestToFetchOptions(reqOpts: Options) {
  const options: f.RequestInit = {
    method: reqOpts.method || 'GET',
    ...(reqOpts.timeout && {timeout: reqOpts.timeout}),
    ...(reqOpts.gzip && {compress: reqOpts.gzip}),
  };

  // ...
}
```

If reqOpts.gzip is false, the code after && will be never executed, and never assigned.

#### Environment details

  - OS:
  - Node.js version: v12.11.1
  - npm version: 6.11.3
  - `teeny-request` version: 5.3.0

#### Steps to reproduce

```javascript
teenyRequest({ uri: '...', gzip: false });
```

or

```javascript
let bigquery = new BigQuery(options);

bigquery.interceptors.push({
  request: function (reqOpts) {
    reqOpts.gzip = false;
    return reqOpts
  }
});
```

**Comment by bcoe** [comment]
@maxiruani thanks for the bug report, this sounds like something we should dig into.
